mysql:
  image: mysql:8.0.12
  ports:
    - "3306:3306"
  expose:
    - 3306
  environment:
    MYSQL_ROOT_PASSWORD: pass
    MYSQL_DATABASE: db
    MYSQL_USER: user
    MYSQL_PASSWORD: pass
  volumes:
      - ./sql/mysql-conf.d:/etc/mysql/conf.d
