// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// confirm between server
type User struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Birth                string   `protobuf:"bytes,3,opt,name=birth,proto3" json:"birth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_26f11bad7a81d2a6, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetBirth() string {
	if m != nil {
		return m.Birth
	}
	return ""
}

type Proreq struct {
	TxId                 string   `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type                 float64  `protobuf:"fixed64,3,opt,name=type,proto3" json:"type,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proreq) Reset()         { *m = Proreq{} }
func (m *Proreq) String() string { return proto.CompactTextString(m) }
func (*Proreq) ProtoMessage()    {}
func (*Proreq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_26f11bad7a81d2a6, []int{1}
}
func (m *Proreq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proreq.Unmarshal(m, b)
}
func (m *Proreq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proreq.Marshal(b, m, deterministic)
}
func (dst *Proreq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proreq.Merge(dst, src)
}
func (m *Proreq) XXX_Size() int {
	return xxx_messageInfo_Proreq.Size(m)
}
func (m *Proreq) XXX_DiscardUnknown() {
	xxx_messageInfo_Proreq.DiscardUnknown(m)
}

var xxx_messageInfo_Proreq proto.InternalMessageInfo

func (m *Proreq) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *Proreq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Proreq) GetType() float64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Proreq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// uses only in response
type Status struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_26f11bad7a81d2a6, []int{2}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (dst *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(dst, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ProreqList struct {
	Req                  []*Proreq `protobuf:"bytes,1,rep,name=req,proto3" json:"req,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ProreqList) Reset()         { *m = ProreqList{} }
func (m *ProreqList) String() string { return proto.CompactTextString(m) }
func (*ProreqList) ProtoMessage()    {}
func (*ProreqList) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_26f11bad7a81d2a6, []int{3}
}
func (m *ProreqList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProreqList.Unmarshal(m, b)
}
func (m *ProreqList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProreqList.Marshal(b, m, deterministic)
}
func (dst *ProreqList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProreqList.Merge(dst, src)
}
func (m *ProreqList) XXX_Size() int {
	return xxx_messageInfo_ProreqList.Size(m)
}
func (m *ProreqList) XXX_DiscardUnknown() {
	xxx_messageInfo_ProreqList.DiscardUnknown(m)
}

var xxx_messageInfo_ProreqList proto.InternalMessageInfo

func (m *ProreqList) GetReq() []*Proreq {
	if m != nil {
		return m.Req
	}
	return nil
}

type UserId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_26f11bad7a81d2a6, []int{4}
}
func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (dst *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(dst, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Judge struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TxId                 string   `protobuf:"bytes,2,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Res                  bool     `protobuf:"varint,3,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Judge) Reset()         { *m = Judge{} }
func (m *Judge) String() string { return proto.CompactTextString(m) }
func (*Judge) ProtoMessage()    {}
func (*Judge) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_26f11bad7a81d2a6, []int{5}
}
func (m *Judge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Judge.Unmarshal(m, b)
}
func (m *Judge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Judge.Marshal(b, m, deterministic)
}
func (dst *Judge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Judge.Merge(dst, src)
}
func (m *Judge) XXX_Size() int {
	return xxx_messageInfo_Judge.Size(m)
}
func (m *Judge) XXX_DiscardUnknown() {
	xxx_messageInfo_Judge.DiscardUnknown(m)
}

var xxx_messageInfo_Judge proto.InternalMessageInfo

func (m *Judge) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Judge) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *Judge) GetRes() bool {
	if m != nil {
		return m.Res
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*Proreq)(nil), "proto.Proreq")
	proto.RegisterType((*Status)(nil), "proto.Status")
	proto.RegisterType((*ProreqList)(nil), "proto.ProreqList")
	proto.RegisterType((*UserId)(nil), "proto.UserId")
	proto.RegisterType((*Judge)(nil), "proto.Judge")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TsukuproClient is the client API for Tsukupro service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TsukuproClient interface {
	NewUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*Status, error)
	EditProf(ctx context.Context, in *Proreq, opts ...grpc.CallOption) (*Status, error)
	SearchProf(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*ProreqList, error)
}

type tsukuproClient struct {
	cc *grpc.ClientConn
}

func NewTsukuproClient(cc *grpc.ClientConn) TsukuproClient {
	return &tsukuproClient{cc}
}

func (c *tsukuproClient) NewUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/proto.Tsukupro/NewUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tsukuproClient) EditProf(ctx context.Context, in *Proreq, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/proto.Tsukupro/EditProf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tsukuproClient) SearchProf(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*ProreqList, error) {
	out := new(ProreqList)
	err := c.cc.Invoke(ctx, "/proto.Tsukupro/SearchProf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TsukuproServer is the server API for Tsukupro service.
type TsukuproServer interface {
	NewUser(context.Context, *User) (*Status, error)
	EditProf(context.Context, *Proreq) (*Status, error)
	SearchProf(context.Context, *UserId) (*ProreqList, error)
}

func RegisterTsukuproServer(s *grpc.Server, srv TsukuproServer) {
	s.RegisterService(&_Tsukupro_serviceDesc, srv)
}

func _Tsukupro_NewUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsukuproServer).NewUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Tsukupro/NewUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsukuproServer).NewUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tsukupro_EditProf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Proreq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsukuproServer).EditProf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Tsukupro/EditProf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsukuproServer).EditProf(ctx, req.(*Proreq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tsukupro_SearchProf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsukuproServer).SearchProf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Tsukupro/SearchProf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsukuproServer).SearchProf(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tsukupro_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Tsukupro",
	HandlerType: (*TsukuproServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewUser",
			Handler:    _Tsukupro_NewUser_Handler,
		},
		{
			MethodName: "EditProf",
			Handler:    _Tsukupro_EditProf_Handler,
		},
		{
			MethodName: "SearchProf",
			Handler:    _Tsukupro_SearchProf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_26f11bad7a81d2a6) }

var fileDescriptor_user_26f11bad7a81d2a6 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0x5d, 0x4b, 0x03, 0x31,
	0x10, 0x6c, 0xee, 0xdb, 0xad, 0x8a, 0x46, 0xc1, 0xd0, 0x17, 0x8f, 0xbc, 0x78, 0x08, 0x16, 0xa9,
	0xbf, 0x41, 0xe4, 0x44, 0xa4, 0x5c, 0xed, 0xab, 0x92, 0x9a, 0xd8, 0x1e, 0x52, 0xef, 0x9a, 0xe4,
	0xb0, 0xfe, 0x0c, 0xff, 0xb1, 0x24, 0x69, 0x6b, 0x4f, 0xe9, 0x53, 0x76, 0x66, 0x37, 0x3b, 0x33,
	0x0b, 0xd0, 0x28, 0x21, 0xfb, 0xb5, 0xac, 0x74, 0x85, 0x43, 0xfb, 0xd0, 0x1c, 0x82, 0xb1, 0x12,
	0x12, 0x9f, 0x41, 0x6c, 0x9a, 0x2f, 0x25, 0x27, 0x28, 0x45, 0xd9, 0x5e, 0x11, 0x19, 0x98, 0x73,
	0x8c, 0x21, 0xf8, 0x60, 0x73, 0x41, 0x3c, 0xcb, 0xda, 0x1a, 0x9f, 0x42, 0x38, 0x29, 0xa5, 0x9e,
	0x11, 0xdf, 0x92, 0x0e, 0xd0, 0x67, 0x88, 0x86, 0xb2, 0x92, 0x62, 0x81, 0x4f, 0x20, 0xd4, 0xcb,
	0xdf, 0x55, 0x81, 0x5e, 0xe6, 0x7c, 0x5b, 0xc1, 0xfb, 0xab, 0xa0, 0xbf, 0x6a, 0x61, 0x97, 0xa1,
	0xc2, 0xd6, 0x86, 0xe3, 0x4c, 0x33, 0x12, 0xa4, 0x28, 0xdb, 0x2f, 0x6c, 0x4d, 0x29, 0x44, 0x23,
	0xcd, 0x74, 0xa3, 0x30, 0x81, 0x78, 0x2e, 0x94, 0x62, 0x53, 0xb1, 0x52, 0x58, 0x43, 0x7a, 0x05,
	0xe0, 0x3c, 0x3c, 0x94, 0x4a, 0xe3, 0x73, 0xf0, 0xa5, 0x58, 0x10, 0x94, 0xfa, 0x59, 0x77, 0x70,
	0xe0, 0x82, 0xf7, 0x5d, 0xbf, 0x30, 0x1d, 0x4a, 0x20, 0x1a, 0x3b, 0x13, 0x87, 0xe0, 0x6d, 0xfc,
	0x7a, 0x25, 0xa7, 0x77, 0x10, 0xde, 0x37, 0x7c, 0x2a, 0x76, 0x1f, 0x66, 0x13, 0xd2, 0xdb, 0x0a,
	0x79, 0x64, 0x14, 0x95, 0x8d, 0x92, 0x18, 0x09, 0x35, 0xf8, 0x46, 0x90, 0x3c, 0xa9, 0xe6, 0xbd,
	0xa9, 0x65, 0x85, 0x2f, 0x20, 0x7e, 0x14, 0x9f, 0xf6, 0xe0, 0xdd, 0x95, 0x1d, 0x03, 0x7a, 0x6b,
	0x6f, 0x2e, 0x1f, 0xed, 0xe0, 0x4b, 0x48, 0x6e, 0x79, 0xa9, 0x87, 0xb2, 0x7a, 0xc3, 0x6d, 0xe3,
	0xff, 0x67, 0xaf, 0x01, 0x46, 0x82, 0xc9, 0xd7, 0x59, 0x6b, 0xda, 0xe5, 0xea, 0x1d, 0xb7, 0x3e,
	0x9b, 0xab, 0xd0, 0xce, 0x24, 0xb2, 0xdc, 0xcd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xba, 0x97,
	0x35, 0xf1, 0x10, 0x02, 0x00, 0x00,
}
