// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// confirm between server
type User struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Birth                string   `protobuf:"bytes,3,opt,name=birth,proto3" json:"birth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_80ad164dee6032e8, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetBirth() string {
	if m != nil {
		return m.Birth
	}
	return ""
}

type Proreq struct {
	TxId                 string   `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type                 int32    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proreq) Reset()         { *m = Proreq{} }
func (m *Proreq) String() string { return proto.CompactTextString(m) }
func (*Proreq) ProtoMessage()    {}
func (*Proreq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_80ad164dee6032e8, []int{1}
}
func (m *Proreq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proreq.Unmarshal(m, b)
}
func (m *Proreq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proreq.Marshal(b, m, deterministic)
}
func (dst *Proreq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proreq.Merge(dst, src)
}
func (m *Proreq) XXX_Size() int {
	return xxx_messageInfo_Proreq.Size(m)
}
func (m *Proreq) XXX_DiscardUnknown() {
	xxx_messageInfo_Proreq.DiscardUnknown(m)
}

var xxx_messageInfo_Proreq proto.InternalMessageInfo

func (m *Proreq) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *Proreq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Proreq) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Proreq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// uses only in response
type Status struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_80ad164dee6032e8, []int{2}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (dst *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(dst, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UserId struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_80ad164dee6032e8, []int{3}
}
func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (dst *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(dst, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Judge struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TxId                 string   `protobuf:"bytes,2,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Res                  bool     `protobuf:"varint,3,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Judge) Reset()         { *m = Judge{} }
func (m *Judge) String() string { return proto.CompactTextString(m) }
func (*Judge) ProtoMessage()    {}
func (*Judge) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_80ad164dee6032e8, []int{4}
}
func (m *Judge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Judge.Unmarshal(m, b)
}
func (m *Judge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Judge.Marshal(b, m, deterministic)
}
func (dst *Judge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Judge.Merge(dst, src)
}
func (m *Judge) XXX_Size() int {
	return xxx_messageInfo_Judge.Size(m)
}
func (m *Judge) XXX_DiscardUnknown() {
	xxx_messageInfo_Judge.DiscardUnknown(m)
}

var xxx_messageInfo_Judge proto.InternalMessageInfo

func (m *Judge) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Judge) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *Judge) GetRes() bool {
	if m != nil {
		return m.Res
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*Proreq)(nil), "proto.Proreq")
	proto.RegisterType((*Status)(nil), "proto.Status")
	proto.RegisterType((*UserId)(nil), "proto.UserId")
	proto.RegisterType((*Judge)(nil), "proto.Judge")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TsukuproClient is the client API for Tsukupro service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TsukuproClient interface {
	NewUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*Status, error)
	EditProf(ctx context.Context, in *Proreq, opts ...grpc.CallOption) (*Status, error)
	SearchProf(ctx context.Context, in *UserId, opts ...grpc.CallOption) (Tsukupro_SearchProfClient, error)
	SendJudge(ctx context.Context, in *Judge, opts ...grpc.CallOption) (*Status, error)
}

type tsukuproClient struct {
	cc *grpc.ClientConn
}

func NewTsukuproClient(cc *grpc.ClientConn) TsukuproClient {
	return &tsukuproClient{cc}
}

func (c *tsukuproClient) NewUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/proto.Tsukupro/NewUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tsukuproClient) EditProf(ctx context.Context, in *Proreq, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/proto.Tsukupro/EditProf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tsukuproClient) SearchProf(ctx context.Context, in *UserId, opts ...grpc.CallOption) (Tsukupro_SearchProfClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Tsukupro_serviceDesc.Streams[0], "/proto.Tsukupro/SearchProf", opts...)
	if err != nil {
		return nil, err
	}
	x := &tsukuproSearchProfClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Tsukupro_SearchProfClient interface {
	Recv() (*Proreq, error)
	grpc.ClientStream
}

type tsukuproSearchProfClient struct {
	grpc.ClientStream
}

func (x *tsukuproSearchProfClient) Recv() (*Proreq, error) {
	m := new(Proreq)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tsukuproClient) SendJudge(ctx context.Context, in *Judge, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/proto.Tsukupro/SendJudge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TsukuproServer is the server API for Tsukupro service.
type TsukuproServer interface {
	NewUser(context.Context, *User) (*Status, error)
	EditProf(context.Context, *Proreq) (*Status, error)
	SearchProf(*UserId, Tsukupro_SearchProfServer) error
	SendJudge(context.Context, *Judge) (*Status, error)
}

func RegisterTsukuproServer(s *grpc.Server, srv TsukuproServer) {
	s.RegisterService(&_Tsukupro_serviceDesc, srv)
}

func _Tsukupro_NewUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsukuproServer).NewUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Tsukupro/NewUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsukuproServer).NewUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tsukupro_EditProf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Proreq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsukuproServer).EditProf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Tsukupro/EditProf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsukuproServer).EditProf(ctx, req.(*Proreq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tsukupro_SearchProf_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserId)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TsukuproServer).SearchProf(m, &tsukuproSearchProfServer{stream})
}

type Tsukupro_SearchProfServer interface {
	Send(*Proreq) error
	grpc.ServerStream
}

type tsukuproSearchProfServer struct {
	grpc.ServerStream
}

func (x *tsukuproSearchProfServer) Send(m *Proreq) error {
	return x.ServerStream.SendMsg(m)
}

func _Tsukupro_SendJudge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Judge)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsukuproServer).SendJudge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Tsukupro/SendJudge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsukuproServer).SendJudge(ctx, req.(*Judge))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tsukupro_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Tsukupro",
	HandlerType: (*TsukuproServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewUser",
			Handler:    _Tsukupro_NewUser_Handler,
		},
		{
			MethodName: "EditProf",
			Handler:    _Tsukupro_EditProf_Handler,
		},
		{
			MethodName: "SendJudge",
			Handler:    _Tsukupro_SendJudge_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SearchProf",
			Handler:       _Tsukupro_SearchProf_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_80ad164dee6032e8) }

var fileDescriptor_user_80ad164dee6032e8 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0xc1, 0x4e, 0x02, 0x31,
	0x10, 0xa5, 0xcb, 0x76, 0x81, 0x11, 0x8d, 0xa9, 0x26, 0x36, 0x9c, 0x48, 0x2f, 0x12, 0x0e, 0xc4,
	0xe8, 0x37, 0x18, 0x83, 0x07, 0x43, 0xba, 0x72, 0xd5, 0x14, 0x3b, 0xc2, 0xc6, 0xc0, 0xae, 0x6d,
	0x37, 0xe2, 0xb7, 0xf9, 0x73, 0x66, 0xdb, 0x5d, 0x02, 0x12, 0x4f, 0x7d, 0x6f, 0x66, 0xfa, 0xe6,
	0xbd, 0x01, 0x28, 0x2d, 0x9a, 0x49, 0x61, 0x72, 0x97, 0x33, 0xea, 0x1f, 0x31, 0x85, 0x78, 0x6e,
	0xd1, 0xb0, 0x2b, 0xe8, 0x54, 0xcd, 0xd7, 0x4c, 0x73, 0x32, 0x24, 0x23, 0x2a, 0x93, 0x8a, 0x4e,
	0x35, 0x63, 0x10, 0x6f, 0xd4, 0x1a, 0x79, 0x34, 0x24, 0xa3, 0x9e, 0xf4, 0x98, 0x5d, 0x02, 0x5d,
	0x64, 0xc6, 0xad, 0x78, 0xdb, 0x17, 0x03, 0x11, 0x2f, 0x90, 0xcc, 0x4c, 0x6e, 0xf0, 0x93, 0x5d,
	0x00, 0x75, 0xdb, 0x46, 0xaa, 0x27, 0x63, 0xb7, 0x9d, 0xea, 0xfd, 0x0d, 0xd1, 0xdf, 0x0d, 0xee,
	0xbb, 0x40, 0x2f, 0x46, 0xa5, 0xc7, 0x55, 0x4d, 0x2b, 0xa7, 0x78, 0x3c, 0x24, 0xa3, 0xbe, 0xf4,
	0x58, 0x08, 0x48, 0x52, 0xa7, 0x5c, 0x69, 0x19, 0x87, 0xce, 0x1a, 0xad, 0x55, 0x4b, 0xac, 0x37,
	0x34, 0x54, 0x70, 0x48, 0xe6, 0x41, 0xf5, 0x0c, 0xa2, 0x5d, 0x96, 0x28, 0xd3, 0xe2, 0x01, 0xe8,
	0x63, 0xa9, 0x97, 0xf8, 0x7f, 0xd2, 0x9d, 0xeb, 0x68, 0xcf, 0xf5, 0x39, 0xb4, 0x0d, 0x5a, 0xef,
	0xad, 0x2b, 0x2b, 0x78, 0xfb, 0x43, 0xa0, 0xfb, 0x6c, 0xcb, 0x8f, 0xb2, 0x30, 0x39, 0xbb, 0x86,
	0xce, 0x13, 0x7e, 0xf9, 0x0b, 0x9e, 0x84, 0xc3, 0x4e, 0x2a, 0x32, 0x38, 0xad, 0x49, 0x30, 0x2c,
	0x5a, 0x6c, 0x0c, 0xdd, 0x7b, 0x9d, 0xb9, 0x99, 0xc9, 0xdf, 0x59, 0xd3, 0x0c, 0xd7, 0x3a, 0x9e,
	0x9d, 0x00, 0xa4, 0xa8, 0xcc, 0xdb, 0xea, 0x60, 0x3a, 0xe4, 0x1a, 0x1c, 0x7e, 0x16, 0xad, 0x1b,
	0xc2, 0xc6, 0xd0, 0x4b, 0x71, 0xa3, 0x43, 0xbc, 0x7e, 0xdd, 0xf7, 0xec, 0x48, 0x7b, 0x91, 0x78,
	0x7e, 0xf7, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xc9, 0xd6, 0x01, 0x97, 0x0b, 0x02, 0x00, 0x00,
}
